# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: João Pedro Dias
email: jpdias@live.com.pt
description: An informatics and computing engineer based on Porto that also loves design and photography. Developer by nature with special interest in security, back-end development and Internet of Things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "jpdias.github.io" # the base hostname & protocol for your site
twitter_username: jpd1as
github_username:  jpdias

# Build settings
markdown: kramdown
