title:        JP Dias
tagline:      'Engineer. Developer. Designer. Photographer.'
description:  'A blog and a Portfolio'
url:          http://jpdias.tk
version:      1.1.1
author:		 
  name:       'JP Dias'
  email:      'jpdias@live.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
