title: "João Pedro Dias"
url: "https://jpdias.me"
baseurl: ""
twitter_username: jpd1as

markdown: kramdown
excerpt_separator: <!--more-->
highlighter: rouge
paginate: 8
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate]


tracking_id: UA-47721282-1

footer: yes

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Blog"
   link: "/blog/"
 - name: "Publications"
   link: "/publications"
 - name: "CurriculumVitae"
   link: "/assets/jpdias.pdf"
 - name: "Contact"
   link: "/contact"

social:
  - name: keybase/jpdias
    icon: fab fa-keybase
    url: https://keybase.io/jpdias
  - name: twitter/jpd1as
    icon: fab fa-twitter
    url: https://twitter.com/jpd1as
  - name: linkedin/joaopdias
    icon: fab fa-linkedin
    url: https://www.linkedin.com/in/joaopdias/
  - name: 500px/jpdias
    icon: fab fa-500px
    url: https://500px.com/jpdias
  - name: instagram/jpdias.photo
    icon: fab fa-instagram
    url: https://www.instagram.com/jpdias.photo
  - name: github/jpdias
    icon: fab fa-github
    url: https://github.com/jpdias
  - name: gitlab/joaopdias
    icon: fab fa-gitlab
    url: https://gitlab.com/joaopdias
  - name: speakerdeck/jpd1as
    icon: fas fa-bullhorn
    url: https://speakerdeck.com/jpdias
  - name: orcid/0000-0001-9066-6436
    icon: fas fa-book-open
    url: https://orcid.org/0000-0001-9066-6436
  - name: gscholar/NYavJ60AAAAJ
    icon: fas fa-graduation-cap
    url: https://scholar.google.pt/citations?user=NYavJ60AAAAJ