title: "Abdelrahman Abdelkader"
url: "https://abdul71.github.io"
baseurl: ""
username: abdul71
twitter_username: abdul_kader71
profile_picture: /images/profile_picture.png

markdown: kramdown
excerpt_separator: <!--more-->
highlighter: rouge
paginate: 8
paginate_path: "/projects/page:num/"

plugins: [rouge,kramdown,jekyll-paginate]

footer: yes

nav:
  - name: "about"
    link: "/"
  - name: "projects"
    link: "/projects/"
  - name: "publications"
    link: "/publications"
  - name: "cv.pdf"
    link: "/assets/Abdelrahman-Abdelkader.pdf"
  - name: "contact"
    link: "/contact"

social:
  - name: twitter/abdul_kader71
    icon: ri-twitter-line
    url: https://twitter.com/abdul_kader71

academic:
  - name: gscholar/NOm01YUAAAAJ
    icon: ai ai-google-scholar
    url: https://scholar.google.pt/citations?user=NOm01YUAAAAJ
  - name: arXiv/Abdelkader%2C+Abdelrahman
    icon: ai ai-arxiv
    url: https://arxiv.org/search/cs?searchtype=author&query=Abdelkader%2C+Abdelrahman

